### ISSUE TITLE
Back up original resolutions file.

### ISSUE THREAD

**Issue by dreambottle** [usr-sse2/RDM#1]
Hey!

First, thanks for picking up this piece of software and adding a few nice features to it!

I have a feature suggestion: when editing resolutions it would be great to display the location of the original resolutions file, that is being used for the display, so that the user can back it up, and not worry about breaking something, while editing.

As a next step, the app could do backup/restore with a button click.

What do you think?

**Comment by Igloo302** [comment]
maybe delete the overrides-displayxxxxxx can turn to default?

**Comment by usr-sse2** [comment]
It can for most displays, but some displays have the override files shipped with macOS (such as Apple Cinema Display or some LG models), so to reset their settings it’s needed to restore the original override plist.
