### ISSUE TITLE
can't change resolution

### ISSUE THREAD

**Issue by ruotianluo** [usr-sse2/RDM#15]
I am able to add the custom resolution. However, if I click the added resolution, nothing happens.
(Some other resolutions work)

The resolution I added is 1600x900+hidpi. I am able to use 1440x900+hidpi. (I was able to use 1980x1080+hidpi, but I think I broke something...)

**Comment by ruotianluo** [comment]
Found problem.
It's the plist generated by RDM is incorrect for some reason.
For example:
on https://comsysto.github.io/Display-Override-PropertyList-File-Parser-and-Generator-with-HiDPI-Support-For-Scaled-Resolutions/
3200x1800+hidpi = <data>AAAMgAAABwgAAAABACAAAA==</data> = <00000c80 00000708 00000001 00200000>
While
RDM generates:
<data>AAAMgAAABwgBh60YAAAAAQ==</data> = <00000c80 00000708 0187ad18 00000001>

**Comment by JonnyTech** [comment]
If it is a RDM bug then can you re-open this issue and hopefully @usr-sse2 will reply?
