### ISSUE TITLE
macOS 11 Big Sur support

### ISSUE THREAD

**Issue by chris1111** [usr-sse2/RDM#16]
Please add support for the latest macOS 11
Thanks

**Comment by ruotianluo** [comment]
how did you solve it?

**Comment by chris1111** [comment]
> how did you solve it?

were did you see solved?

**Comment by ruotianluo** [comment]
You closed the issue so I thought it was solved.

**Comment by chris1111** [comment]
> You closed the issue so I thought it was solved.

I closed because no response
