### ISSUE TITLE
Am I using this software correctly?

### ISSUE THREAD

**Issue by niccolomineo** [usr-sse2/RDM#17]
My ultrawide monitor (LG WL500) supports 2560x1080 natively. Due to this res not being shown by MacOs out of the box, I decided to try RDM. The problem is that setting up that res (I also enable HiDPI), leads to have two large black bands at the top and at the bottom of the screen. Any suggestions on what I may be doing wrong?

Thanks.

**Comment by usr-sse2** [comment]
>My ultrawide monitor (LG WL500) supports 2560x1080 natively. Due to this res not being shown by MacOs out of the box, I decided to try RDM. The problem is that setting up that res (I also enable HiDPI), leads to have two large black bands at the top and at the bottom of the screen. Any suggestions on what I may be doing wrong? ...

@niccolomineo RDM can add scaled resolutions if the native resolution is working, but if the native resolution doesn’t work, then you should add a patched EDID manually or add resolution with SwitchResX. Is it on a Mac or a hackintosh?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by niccolomineo** [comment]
It's a 2018 13" Macbook Pro. I would like to accomplish this without a third-party software, if possible. I have a few questions:

- Base on your experience, could it be a cable issue? If so, do you have any suggestions on what kind of adapter and/or cable to buy (this is an HDMI-only screen and my MBP has USB-C ports only)?
- I exported an EDID via SwitchResX (which I would be keen not to depend on, if possible). Do you know if I can do anything with it?
- I entered a custom res in SwitchResX, but, after rebooting, it won't activate, while showing a not very promising status message:
<img width="592" alt="Schermata 2020-07-21 alle 00 33 13" src="https://user-images.githubusercontent.com/5409469/87993008-ca648f00-cae9-11ea-95de-a27e4cde817e.png">

**Comment by niccolomineo** [comment]
I exported an EDID via SwitchResX (which I would be keen not to depend on, if possible). Do you know if I can do anything with it?

**Comment by niccolomineo** [comment]
Ok, I (rather blindly) bought a 4K HDMI adapter off Amazon and it's working! I got the 2560x1080. So I guess there's hardly a way to do without the proper physical HDMI adapter.
