### ISSUE TITLE
Resolution editing not set

### ISSUE THREAD

**Issue by chris1111** [usr-sse2/RDM#2]
running macOS Mojave 10.14 
I dont have same image with you about editing resolution Display
trying to set 1600x900 and this is what is set on the setup menue
#### Screenshot 
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu147.png)
Also the resolution not appear in the list of choice

**Comment by usr-sse2** [comment]
Really, seems that I messed up the saving code while refactoring it. New release will be available today.

**Comment by usr-sse2** [comment]
I replaced the 2.3.1 version on Releases page with an updated one, please check.

**Comment by chris1111** [comment]
Are you release this new update because I am not able to build the app on High Sierra
or send me a build testing app
thanks

**Comment by usr-sse2** [comment]
I replaced the binary package, download the RDM.app.zip from Releases page

**Comment by chris1111** [comment]
Man its work verry well now on High Sierra and I will test  later on Mojave
Thank you very much 
#### Screenshot 
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/119.png)
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu148.png)

**Comment by usr-sse2** [comment]
By adding 1600x900 HiDPI you actually added 800x450⚡️ and 1600x900. Try adding 3200x1800 HiDPI, you’lol get a 1600x900⚡️ and 3200x1800. That is the way OS interprets the plots.

**Comment by chris1111** [comment]
Ok got it 3200x1800  
thanks 
What about 1600x900 Lightning ⚡️ ?
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/215.png)
![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/120.png)

**Comment by chris1111** [comment]
You know what Now I have second stage Logo perfect resolution with a small AppleBoot image

EDIT ***  Mojave OK ![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/24649310.gif)
EDIT 2 ***
Lightning is not show in macOS Mojave but its work 

![Modular Image Creation](https://i25.servimg.com/u/f25/18/50/18/69/captu149.png)
