### ISSUE TITLE
Installation error. Mojave

### ISSUE THREAD

**Issue by gadlevsky** [usr-sse2/RDM#40]
An error occured; try again

** ARCHIVE FAILED **

The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
error: archive not found at path '/var/folders/w3/ktbzdxv53nn4x6l6dr5cmbl40000gn/T/tmp.so1aPA29/RDM.xcarchive'
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

**Comment by cuong-dang** [comment]
I just ran into this issue yesterday. You should launch Xcode once after installation so it could install additional components. After that I believe you should be able to build successfully.
