### ISSUE TITLE
Fix incorrect resolution for internal display

### ISSUE THREAD

**Issue by nawe19** [usr-sse2/RDM#43]
I was trying to use this to fix some sharpness issues on my external monitor, I did something wrong, and now my internal Macbook display things its something else, and has the wrong resolution options. How can I fix this?  

![image](https://user-images.githubusercontent.com/51139645/135771653-eedb82f6-cf72-466a-945f-f1d253f6da58.png)
![image](https://user-images.githubusercontent.com/51139645/135771693-445f3ec1-9114-4655-bc8b-14dc8c2d5df6.png)

**Comment by trungphamquoc96** [comment]
I have the same problem as well. It's not too much of a hassle, but the bug just feel very weird though.

**Comment by usr-sse2** [comment]
Remove `/Library/Displays/Contents/Resources/Overrides/` folder.
