### ISSUE TITLE
Can't open in macOS Monterey

### ISSUE THREAD

**Issue by haifahrul** [usr-sse2/RDM#44]
Can not open the application on macOS Monterey

![image](https://user-images.githubusercontent.com/6553704/139355593-d7d2ed89-6579-4d49-a8ad-8cbe3fcd29a6.png)

**Comment by usr-sse2** [comment]
Ctrl-click it and click Open while holding Ctrl. It has been so for all unsigned applications since Catalina. I won't pay $99/year for a developer account just to sign this app.
