### ISSUE TITLE
Editing display override plist is impossible in macOS Catalina

### ISSUE THREAD

**Issue by usr-sse2** [usr-sse2/RDM#8]
System volume is readonly in macOS Catalina, so editing display override plist is impossible.

**Comment by YangAi** [comment]
Try this command before copy the file.

`sudo mount -uw /`

**Comment by ruotianluo** [comment]
The plist can be overridden following the instruction above. However, the added resolution is not shown in the list after rebooting.

**Comment by mbeaudru** [comment]
> Try this command before copy the file.

In other words, put this command in your terminal before creating your custom resolution and after restart it will work as intended 👍 

I wanted to reword this because I really wasn't sure the command was going to work, tried in desperation and it worked  🎉 thanks again @YangAi

**Comment by usr-sse2** [comment]
Version 2.3.2 mounts the ROSV read-write before copying the override plist.
